# Generated by Django 4.0.4 on 2022-06-12 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='bac_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='transfer',
            name='bac_mean',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='transfer',
            name='bac_number',
            field=models.IntegerField(default=1111111),
        ),
        migrations.AddField(
            model_name='transfer',
            name='birth_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='transfer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='wilaya',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
