# Generated by Django 4.0.4 on 2022-06-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_transfer_bac_date_transfer_bac_mean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='orginal_uni',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
