# Generated by Django 4.0.4 on 2022-06-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_transfer_orginal_uni'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='level',
            field=models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='orginal_uni',
            field=models.CharField(choices=[('MI', 'MI'), ('sport', 'sport'), ('eco', 'eco')], max_length=400, null=True),
        ),
    ]
