# Generated by Django 4.0.4 on 2022-06-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
