# Generated by Django 4.0.4 on 2022-06-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_approval_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='files',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
