# Generated by Django 4.0.4 on 2022-06-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_transfer_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
